import Link from "next/link";
import { getLegalConfig } from "../lib/legal-config";

export function LegalPage({ kind }: { kind: "privacy" | "terms" }) {
  const privacy = kind === "privacy";
  const legal = getLegalConfig();
  return <main className="legal-page"><header><Link href="/">Housora</Link><span>Last updated August 29, 2026</span></header><article>
    <span className="eyebrow">Legal</span><h1>{privacy ? "Privacy Policy" : "Terms of Service"}</h1>
    <p className="legal-lead">{privacy ? "This policy explains what Housora collects, why it is used, who processes it, and the choices available to you." : "These terms govern access to Housora’s AI design, image, segmentation, 3D, AR, storage, subscription, and credit services."}</p>
    {!legal.ready ? <div className="legal-config-warning" role="alert"><strong>Operator details are not yet configured.</strong><p>This deployment is not ready for public launch. Missing: {legal.missing.join(", ")}.</p></div> : null}
    {privacy ? <PrivacyContent /> : <TermsContent />}
    {legal.ready ? <Section title="Operator and contact"><p>{legal.legalName}<br />{legal.legalAddress}</p><p>Support: <a href={`mailto:${legal.supportEmail}`}>{legal.supportEmail}</a><br />Privacy: <a href={`mailto:${legal.privacyEmail}`}>{legal.privacyEmail}</a></p><p>Governing jurisdiction: {legal.jurisdiction}{legal.salesGeo ? `. Sales availability: ${legal.salesGeo}.` : "."}</p></Section> : null}
  </article><footer><Link href="/privacy">Privacy Policy</Link><Link href="/terms">Terms of Service</Link><Link href="/">Back to Housora</Link></footer></main>;
}

function PrivacyContent() { return <>
  <Section title="1. Information we collect"><p>We process account information supplied through Clerk; projects, prompts, uploaded and generated images, detected objects, 3D files and saved designs; billing status and transaction identifiers supplied by Whop; preferences and support communications; and essential technical logs needed for security and reliability.</p><p>Optional PostHog product analytics are collected only when enabled in Settings. Session replay is disabled. Passwords and complete payment-card details are handled by their respective providers and are not stored by Housora.</p></Section>
  <Section title="2. How we use information"><p>We use information to authenticate users, provide and improve design features, store projects, measure and fulfill credits, prevent abuse, support users, maintain security, comply with law, and send requested service communications. Marketing communications require a separate choice.</p></Section>
  <Section title="3. AI and service providers"><p>Inputs required for a chosen action may be sent to xAI Grok for image generation and editing, Meta SAM hosted on Modal for segmentation, Tripo for 3D generation, and Google model-viewer code on your device for 3D/AR display. Convex stores application data, Clerk provides identity, Whop processes payments, and PostHog receives optional product analytics only when enabled. Their processing is limited to providing the requested service under their own terms and our configurations.</p></Section>
  <Section title="4. Legal bases and sharing"><p>Depending on your location, processing relies on performance of a contract, legitimate interests in operating and securing Housora, consent for optional analytics or marketing, and legal obligations. We do not sell personal information. We share only what is necessary with processors, professional advisers, authorities when legally required, or a successor in a corporate transaction.</p></Section>
  <Section title="5. Retention, security, and transfers"><p>We keep account and project data while your account is active and as needed to deliver the service. Billing, fraud-prevention and legal records may be retained longer where required. Data may be processed in countries other than yours with appropriate contractual and technical safeguards. No online service can guarantee absolute security.</p></Section>
  <Section title="6. Your choices and rights"><p>You may update account details, control analytics and notifications, download your generated outputs, and request access, correction, deletion, restriction, objection, portability, or withdrawal of consent where applicable. You may also complain to your local data-protection authority. Account deletion and security controls are available through Settings.</p></Section>
  <Section title="7. Children, changes, and contact"><p>Housora is not directed to children under 13, or the higher minimum age required in their country. We may update this policy and will provide notice when changes are material. The operator’s legal name, postal address, privacy email, governing jurisdiction, and any required data-protection representative must be published in the deployment’s legal configuration before public launch.</p></Section>
  </>; }

function TermsContent() { return <>
  <Section title="1. Eligibility and accounts"><p>You must be legally able to enter a contract and meet the minimum age in your country. You are responsible for accurate account information, safeguarding access, authorized activity, and promptly reporting suspected misuse.</p></Section>
  <Section title="2. The service and AI limitations"><p>Housora provides AI-assisted concepts, edits, segmentation, 3D models and AR previews. Outputs may be inaccurate, incomplete, visually inconsistent, or unsuitable for construction. They are not architectural, engineering, safety, code-compliance, accessibility, valuation, or other professional advice. Verify dimensions, materials, rights, structure, utilities and regulations with qualified professionals before acting.</p></Section>
  <Section title="3. Content and acceptable use"><p>You retain rights you hold in your inputs and receive rights in outputs to the extent permitted by law and provider terms. You grant Housora a limited license to host, process, transmit and display content solely to provide and secure the service. You must have permission for uploaded content and must not submit illegal, harmful, infringing, private without consent, deceptive, abusive, malicious, or security-compromising material.</p></Section>
  <Section title="4. Plans, credits, billing and refunds"><p>Prices, billing periods, taxes and included credits are shown at checkout. Whop processes payment. Plan credits refresh as described and do not roll over; separately purchased credits are used after plan credits and expire 12 months after purchase. Credits have no cash value and cannot be transferred. Failed, refunded, disputed or reversed payments may remove associated access or credits. Cancellation stops future renewal and access continues only through the paid period unless law requires otherwise. Refunds follow the checkout terms and mandatory consumer law.</p></Section>
  <Section title="5. Third-party services"><p>Housora depends on services including Clerk, Convex, Whop, xAI Grok, Meta SAM hosted on Modal, Tripo, PostHog when enabled, and browser/AR platform capabilities. Availability and outputs may be affected by those services. Their separate terms may apply where you interact with them directly.</p></Section>
  <Section title="6. Suspension and termination"><p>We may limit or suspend access to protect users, investigate abuse, comply with law, address non-payment, or preserve service integrity. You may stop using Housora or delete your account. Clauses that by nature should survive—including payment, ownership, disclaimers, liability and disputes—continue after termination.</p></Section>
  <Section title="7. Disclaimers and liability"><p>The service is provided on an “as available” basis to the maximum extent permitted by law. Housora does not guarantee uninterrupted access, particular design results, or fitness for construction. Any liability cap, warranty exclusion, indemnity, governing law, venue, mandatory consumer rights, business identity, notice email and geographic sales restrictions must be completed for the operator’s jurisdiction and reviewed by qualified counsel before public launch; nothing here excludes liability that cannot legally be excluded.</p></Section>
  <Section title="8. Changes and contact"><p>We may change the service or these terms. Material changes will be announced before they take effect when required. Continued use after the effective date means acceptance where legally permitted. The operator’s complete legal identity and contact details must appear here before launch.</p></Section>
  </>; }

function Section({ title, children }: { title: string; children: React.ReactNode }) { return <section><h2>{title}</h2>{children}</section>; }
